name: remote_content_explorer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  dio: ^5.9.2
  flutter:
    sdk: flutter
  retrofit: ^4.9.2
  riverpod: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^10.2.5
  json_serializable: ^6.13.1
  build_runner: ^2.14.1


flutter:
  uses-material-design: true
